modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
 
[[mods]]
modId="battlegear"
version="0.0.1 Pre-Alpha"
displayName="Mine & Blade: Battlegear III"
logoFile="battlegear.png"
credits="Thank you to nerd-boy, amedwards, and GotoLink for the original mod(s)!"
authors="rainbowdestiny, Bug1312"
description='''
A remake of the remake of Minecraft's coolest shield and war weapons mod!
''' 
 